### ISSUE TITLE
Bug: `ProgressBar` not redrawing when using `ParallelIterator` from `rayon`

### ISSUE THREAD

**Issue by frereit** [athre0z/zzz#4]
I am trying to create a `ProgressBar` over an iterator created using the [rayon](https://docs.rs/rayon/latest/rayon/index.html) crate:

```rust
use std::thread;
use std::time::Duration;

use rayon::prelude::*;
use zzz::ProgressBar;

fn main() {
    let elems = vec![0; 10000];
    let pb = ProgressBar::with_target(elems.len());
    elems.par_iter().for_each(|_| {
        pb.add_sync(1);
        thread::sleep(Duration::from_millis(5));
    });
}
```
```
[dependencies]
rayon = "1.7.0"
zzz = "0.2.1"
```

However, this does not seem to work as expected. The progress bar appears:

```
  0.04% |▏                                                                                                 | 4.00/10.00K [00:00:01] (8.91K it/s
```

but is then not redrawn until the iterator completes:

```
100.00% |███████████████████████████████████████████████████████████████████████████████████████████████▏| 10.00K/10.00K [00:00:00] (1.17K it/s)
```

When replacing the `.par_iter()` with a normal `.iter()`, this works as expected and the progress bar is smoothly redrawn. Is this an issue with the implementation of `add_sync` inside `zzz`?

This *might* be user error, so apologies in advance if that is the case.

Edit: whoops, I accidentally submitted the issue too early. sorry about that.

**Comment by athre0z** [comment]
Hmm, yeah. I think the issue is that you're calling `add_sync(1)` at the start of the loop instead of the end. The first 16 iterations are used to determine the expected general pace of the loop and to calculate after how many iterations we should next redraw and reconsider the refresh rate. If you have >16 cores and `add_sync` at loop start, it will essentially immediately count to 16 and make `zzz` assume that the loop is incredibly fast, so the "next print" amount is set to a very high value.

This is essentially the inherent trade-off of this low-overhead approach for determining when to draw next: if the first few iterations are a lot faster than the rest it might not redraw for quite a while. The alternative is to retrieve and compare time on every loop like `indicatif` does, but that will noticeably slow down simple loops -- the very reason why `zzz` exists in the first place.
